title = "Kris - The Coding Unicorn"
author = "Kris - The Coding Unicorn"
copyright = "2023 - Powered by Hugo"
description = "Welcome to my tech corner! ü§ó \nI preach about all things cloud native, green tech and cats üêà \nCheck \"Blog\" for new posts and \"About\" for my community involvement ü¶Ñ"
profilePicture = "images/profile.jpg"
bmcButton = "images/bmc_button.png"
bmcUrl = "https://www.buymeacoffee.com/kristhecodingu1"
keywords = ""
favicon = "favicons/"
displayMode = "dark"
readMore = true
enableEmoji = true
disableThemeSwitcher = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# example ["css/custom.css"]
customCss = ["css/syntax.css"]

# example ["js/custom.js"]
customJs = [] 

mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mleaglnw"

# Google Site Verify
googleSiteVerify = "OQXmc6vSYyn6I-aGZoI6GH2M6CdM4NjmwulDqvvNCQA"

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[umami]
serverURL = "umami-guidemetothemoon.vercel.app"
id = "9dd30a0e-3918-4513-b61d-4dd81e20ed4b"
trackerScriptName = "18352c56e4b049f69a24fbae0ca62b4f.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/krisde"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/guidemetothemoon"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/kristhecodingu1"

[[socialIcons]]
icon = "fas fa-bullhorn"
title = "Sessionize"
url = "https://sessionize.com/kristina-devochko"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/guidemetothemoon"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "/contact/"

[[socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = "https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Fkristhecodingunicorn.com%2Findex.xml"

[[socialIcons]]
icon = "fas fa-mask"
title = "Azure Heroes"
url = "https://www.azureheroes.community/user/15391"

[[socialIcons]]
icon = "fas fa-cloud"
title = "Microsoft MVP"
url = "https://mvp.microsoft.com/en-us/PublicProfile/5004929?fullName=Kristina%20Devochko"